[RMPsetup]
MaxRule=7

[Rule1]
#RuleName=DISCONNT
#DisableRule=true

#SrcCnt=1
#SrcSvc1=DISCONNT

#FieldCount=0

#ProcCnt=0

#Comment=""
[Rule2]
RuleName=TIMEOUT 처리
DisableRule=false

SrcCnt=1
SrcSvc1=CLOSE_ALL

FieldCount=0

ProcCnt=1

Proc1Disable=false
Proc1Replace=no
Proc1ActionCnt=2

Proc1Action1Kind=TGLaction
Proc1Action1DisableAc=false
Proc1Action1TGLaction=CLS_SVR
Proc1Action1TCPinfoInput=frame
Proc1Action1TCPinfoOutput=succession
Proc1Action1SuccessJumpProc=-1
Proc1Action1FailJumpProc=-1

Proc1Action2Kind=TGLaction
Proc1Action2DisableAc=false
Proc1Action2TGLaction=CLS_CLI
Proc1Action2TCPinfoInput=frame
Proc1Action2TCPinfoOutput=succession
Proc1Action2SuccessJumpProc=-1
Proc1Action2FailJumpProc=-1

Proc1Comment=""
Comment=""

[Rule3]
RuleName=CLI_세션키 송신
DisableRule=false

SrcCnt=1
SrcSvc1=CLI_SKEY

FieldCount=0

ProcCnt=1

Proc1Disable=false
Proc1Replace=no
Proc1ActionCnt=1

Proc1Action1Kind=TGLaction
Proc1Action1DisableAc=false
Proc1Action1TGLaction=SND_CLI
Proc1Action1TCPinfoInput=frame
Proc1Action1TCPinfoOutput=succession
Proc1Action1RSCB=-1
Proc1Action1RFCB=-1

Proc1Comment=""
Comment="client 세션키교환 송신 처리 (수신처리는 전문수신 처리에서 일괄 처리)"

[Rule4]
RuleName=SVR_세션키 송신
DisableRule=false

SrcCnt=1
SrcSvc1=SVR_SKEY

FieldCount=0

ProcCnt=1

Proc1Disable=false
Proc1Replace=no
Proc1ActionCnt=1

Proc1Action1Kind=TGLaction
Proc1Action1DisableAc=false
Proc1Action1TGLaction=SND_SVR
Proc1Action1TCPinfoInput=frame
Proc1Action1TCPinfoOutput=succession
Proc1Action1RSCB=-1
Proc1Action1RFCB=-1

Proc1Comment=""
Comment="server 세션키교환 송신 처리 (수신처리는 전문수신 처리에서 일괄 처리)"

[Rule5]
RuleName=전문송신 처리
DisableRule=false

SrcCnt=1
SrcSvc1=SNDMSG_ISO

FieldCount=0

ProcCnt=2

Proc1Disable=false
Proc1Replace=no
Proc1ActionCnt=2

Proc1Action1Kind=TGLaction
Proc1Action1DisableAc=false
Proc1Action1TGLaction=SND_CLI
Proc1Action1TCPinfoInput=frame
Proc1Action1TCPinfoOutput=succession
Proc1Action1FailMethod=procnoreplace
Proc1Action1FailJumpProc=2

#Proc1Action2Kind=callback
#Proc1Action2DisableAc=true
#Proc1Action2CallbackName=CF_ImgLogSend
Proc1Action2SuccessJumpProc=-1
Proc1Action2FailJumpProc=2

Proc1Comment="대외 전문 생성 및 전송 처리"

#Proc2Disable=true
#Proc2Replace=no
#Proc2ActionCnt=1

#Proc2Action1Kind=callback
#Proc2Action1DisableAc=true
#Proc2Action1CallbackName=CF_SndErrProc
#Proc2Action1FailMethod=procnoreplace
#Proc2Action1SuccessJumpProc=-1
#Proc2Action1FailJumpProc=-1

#Proc2Comment="전문 송신 오류 내역 로깅 처리"
Comment="기관 전문 송신처리 부"

[Rule6]
RuleName=전문수신 처리
DisableRule=false

SrcCnt=2
SrcSvc1=SVR
SrcSvc2=CLI

FieldCount=0

ProcCnt=2

Proc1Disable=false
Proc1Replace=yes
Proc1ActionCnt=1

Proc1Action1Kind=callback
Proc1Action1CallbackName=CF_ReceiveMessage
Proc1Action1DisableAc=false
Proc1Action1FailJumpProc=2
Proc1Action1Comment="암호메시지 수신"

Proc1Comment=""

#Proc2Disable=true
#Proc2Replace=no
#Proc2ActionCnt=1

#Proc2Action1Kind=callback
#Proc2Action1DisableAc=true
#Proc2Action1CallbackName=CF_SndErrProc
#Proc2Action1FailMethod=procnoreplace
#Proc2Action1SuccessJumpProc=-1
#Proc2Action1FailJumpProc=-1

#Proc2Comment=""

Comment="기관 전문 수신처리 부"
