[TGLinfo]
Type=tcpip
RCNXtimerMax=1024
RCNXtimerMask=0x20000000
VRFtimerMax=10000
VRFtimerMask=0x30000000

SectionCount=3
Section1=SND_RP
Section2=CLS_RP
Section3=LSN_RP

[CallbackDefine]
TotalCount=6
CallbackFuncName1=CF_ACloseSession
CallbackFuncName2=CF_APortConnect
CallbackFuncName3=CF_UpdateSendCnt
CallbackFuncName4=CF_UpdateRecvCnt
CallbackFuncName5=CF_Decrypt
CallbackFuncName6=CF_Encrypt

[StartProcedure]
TotalCount=1
JobSection1=LSN_RP

[VirtualPortMap]
TotalCount=0

[SND_RP]
ActionType=SendPacket
SessionGroup=SG_RP
SendMethod=SLIL
SessionPattern=
IPPattern=
DataVerifySection=

[CLS_RP]
ActionType=CloseSession
SessionGroup=SG_RP

[LSN_RP]
ActionType=ListenPort
LocalPort=23721
Backlog=32

[PassiveAction]
CloseEventCount=1
RcvEventCount=1
AcceptEventCount=1

[CloseEvent1]
SessionGroup=SG_RP
ProcCount=0

[RcvEvent1]
SessionGroup=SG_RP
MaxFragmentation=100
FragmentSleep=100
FrameType=HeaderBody
HeaderSize=4
SizeDefPos=0
SizeDefLength=4
SizeDefType=strnum
SizeDefRange=4
ProcCount=1
Proc1Condition=success
Proc1ConditionValue=
Proc1ActionCount=1
Proc1Action1Type=RMPaction
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Src=RCVMSG
Proc1Action1FrameType=FrameOnly

[AcceptEvent1]
LocalPortCount=1
LocalPort1=23721
PeerIPaddrCount=1
PeerIPaddr1=172.18.220.80
SessionGroup=SG_RP
SessionGroupDefine=PIPP
#서버 세션 수 제한기능 (0:모두 허용 1:세션개수제한 2:제한초과시 이전세션종료)
ProcCount=0

