[TGLinfo]
Type=tcpip
RCNXtimerMax=1024
RCNXtimerMask=0x20000000
VRFtimerMax=10000
VRFtimerMask=0x30000000

SectionCount=6
Section1=LSN_SVR
Section2=SND_SVR
Section3=CLS_SVR
Section4=CNT_CLI
Section5=SND_CLI
Section6=CLS_CLI

[CallbackDefine]
TotalCount=2
CallbackFuncName1=CF_APortConnect_HS
CallbackFuncName2=CF_ACloseSession

[StartProcedure]
TotalCount=2
JobSection1=LSN_SVR
JobSection2=CNT_CLI

[VirtualPortMap]
TotalCount=0

[LSN_SVR]
ActionType=ListenPort
LocalPort=23750
Backlog=32

[SND_SVR]
ActionType=SendPacket
SessionGroup=SVR_SG
SendMethod=SLIL
SessionPattern=
IPPattern=
DataVerifySection=

[CLS_SVR]
ActionType=CloseSession
SessionGroup=SVR_SG

[CNT_CLI]
ActionType=ConnectPort
LocalPortCount=1
LocalPort1=1.234.25.131:-1
PeerIPaddrCount=1
PeerIPaddr1=1.234.25.131
PeerPortCount=1
PeerPort1=23750
Type=Sync
Timeout=1000
SessionGroup=CLI_SG
SessionGroupDefine=PIPP
ProcCount=2
Proc1Condition=success
Proc1ConditionValue=
Proc1ActionCount=1
Proc1Action1Type=callback
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Callback=CF_APortConnect_HS
Proc2Condition=UnderCountPerAll
Proc2ConditionValue=1
Proc2ActionCount=1
Proc2Action1Type=retrycnx
Proc2Action1InfoInput=succession
Proc2Action1InfoOutput=succession
Proc2Action1RetryCount=-1
Proc2Action1RetryInterval=1000
Proc2Action1RetrySection=CNT_CLI

[SND_CLI]
ActionType=SendPacket
SessionGroup=CLI_SG
SendMethod=SLIL
SessionPattern=
IPPattern=
DataVerifySection=

[CLS_CLI]
ActionType=CloseSession
SessionGroup=CLI_SG
ProcCount=1
Proc1Condition=success
Proc1ConditionValue=
Proc1ActionCount=2
Proc1Action1Type=callback
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Callback=CF_ACloseSession
Proc1Action2Type=Section
Proc1Action2InfoInput=none
Proc1Action2InfoOutput=succession
Proc1Action2Section=CNT_CLI

[PassiveAction]
CloseEventCount=2
RcvEventCount=2
AcceptEventCount=1

[CloseEvent1]
SessionGroup=SVR_SG
ProcCount=1
Proc1Condition=noc
Proc1ConditionValue=
Proc1ActionCount=1
Proc1Action1Type=callback
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Callback=CF_StopPoll

[CloseEvent2]
SessionGroup=CLI_SG
ProcCount=1
Proc1Condition=noc
Proc1ConditionValue=
Proc1ActionCount=3
Proc1Action1Type=callback
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Callback=CF_ACloseSession
Proc1Action2Type=callback
Proc1Action2InfoInput=succession
Proc1Action2InfoOutput=succession
Proc1Action2Callback=CF_StopPoll
Proc1Action3Type=retrycnx
Proc1Action3InfoInput=succession
Proc1Action3InfoOutput=succession
Proc1Action3RetryCount=-1
Proc1Action3RetryInterval=10000
Proc1Action3RetrySection=CNT_CLI

[RcvEvent1]
SessionGroup=SVR_SG
MaxFragmentation=100
FragmentSleep=100
FrameType=HeaderBody
HeaderSize=5
SizeDefPos=0
SizeDefLength=5
SizeDefType=strnum
SizeDefRange=5
ProcCount=1
Proc1Condition=success
Proc1ConditionValue=
Proc1ActionCount=1
Proc1Action1Type=RMPaction
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Src=RCV_SVR
Proc1Action1FrameType=FrameOnly

[RcvEvent2]
SessionGroup=CLI_SG
MaxFragmentation=100
FragmentSleep=100
FrameType=HeaderBody
HeaderSize=5
SizeDefPos=0
SizeDefLength=5
SizeDefType=strnum
SizeDefRange=5
ProcCount=1
Proc1Condition=success
Proc1ConditionValue=
Proc1ActionCount=1
Proc1Action1Type=RMPaction
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Src=RCV_CLI
Proc1Action1FrameType=FrameOnly

[AcceptEvent1]
LocalPortCount=1
LocalPort1=23750
PeerIPaddrCount=1
PeerIPaddr1=1.234.25.131
SessionGroup=SVR_SG
SessionGroupDefine=PIPPLP
# 서버 세션 수 제한기능 - 0:제한없음 1:제한(최종세션종료) 2:제한(최초세션종료)
SessionLimit=2     # 최초 세션교체
ProcCount=0

