[TGLinfo]
Type=tcpip
RCNXtimerMax=1024
RCNXtimerMask=0x20000000
VRFtimerMax=10000
VRFtimerMask=0x30000000

SectionCount=6
Section1=CNT_CLI1
Section2=SND_CLI1
Section3=CLS_CLI1
Section4=LSN_SVR1
Section5=SND_SVR1
Section6=CLS_SVR1

[CallbackDefine]
TotalCount=5
CallbackFuncName1=CF_APortConnect
CallbackFuncName2=CF_Encrypt
CallbackFuncName3=CF_Decrypt
CallbackFuncName4=CF_ACloseSession
CallbackFuncName5=CF_StopPoll

[StartProcedure]
TotalCount=2
JobSection1=CNT_CLI1
JobSection2=LSN_SVR1

[VirtualPortMap]
TotalCount=0

[CNT_CLI1]
ActionType=ConnectPort
LocalPortCount=1
LocalPort1=130.12.3.32:-1
PeerIPaddrCount=1
PeerIPaddr1=172.18.220.60
PeerPortCount=1
PeerPort1=23720
Type=Sync
Timeout=1000
SessionGroup=SG_CLI1
SessionGroupDefine=PIPP
ProcCount=2
Proc1Condition=success
Proc1ConditionValue=
Proc1ActionCount=1
Proc1Action1Type=callback
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Callback=CF_APortConnect
Proc2Condition=UnderCountPerAll
Proc2ConditionValue=1
Proc2ActionCount=1
Proc2Action1Type=retrycnx
Proc2Action1InfoInput=none
Proc2Action1InfoOutput=succession
Proc2Action1RetryCount=-1
Proc2Action1RetryInterval=10000
Proc2Action1RetrySection=CNT_CLI1

[SND_CLI1]
ActionType=SendPacket
SessionGroup=SG_CLI1
SendMethod=SLIL
SessionPattern=
IPPattern=
DataVerifySection=

[CLS_CLI1]
ActionType=CloseSession
SessionGroup=SG_CLI1
ProcCount=1
Proc1Condition=success
Proc1ConditionValue=
Proc1ActionCount=2
Proc1Action1Type=callback
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Callback=CF_ACloseSession
Proc1Action2Type=Section
Proc1Action2InfoInput=none
Proc1Action2InfoOutput=succession
Proc1Action2Section=CNT_CLI1

[LSN_SVR1]
ActionType=ListenPort
LocalPort=23720
Backlog=32

[SND_SVR1]
ActionType=SendPacket
SessionGroup=SG_SVR1
SendMethod=SLIL
SessionPattern=
IPPattern=
DataVerifySection=

[CLS_SVR1]
ActionType=CloseSession
SessionGroup=SG_SVR1

[PassiveAction]
CloseEventCount=2
RcvEventCount=2
AcceptEventCount=1

[CloseEvent1]
SessionGroup=SG_CLI1
ProcCount=1
Proc1Condition=noc
Proc1ConditionValue=
Proc1ActionCount=2
Proc1Action1Type=callback
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Callback=CF_ACloseSession
Proc1Action2Type=retrycnx
Proc1Action2InfoInput=succession
Proc1Action2InfoOutput=succession
Proc1Action2RetryCount=-1
Proc1Action2RetryInterval=10000
Proc1Action2RetrySection=CNT_CLI1

[CloseEvent2]
SessionGroup=SG_SVR1
ProcCount=1
Proc1Condition=noc
Proc1ConditionValue=
Proc1ActionCount=1
Proc1Action1Type=callback
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Callback=CF_StopPoll

[RcvEvent1]
SessionGroup=SG_CLI1
MaxFragmentation=1000
FragmentSleep=10
FrameType=HeaderBody
HeaderSize=200
SizeDefPos=0
SizeDefLength=5
SizeDefType=strnum
SizeDefRange=200
ProcCount=1
Proc1Condition=success
Proc1ConditionValue=
Proc1ActionCount=1
Proc1Action1Type=RMPaction
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Src=RcvCli1
Proc1Action1FrameType=FrameOnly

[RcvEvent2]
SessionGroup=SG_SVR1
MaxFragmentation=1000
FragmentSleep=10
FrameType=HeaderBody
HeaderSize=200
SizeDefPos=0
SizeDefLength=5
SizeDefType=strnum
SizeDefRange=200
ProcCount=1
Proc1Condition=success
Proc1ConditionValue=
Proc1ActionCount=1
Proc1Action1Type=RMPaction
Proc1Action1InfoInput=succession
Proc1Action1InfoOutput=succession
Proc1Action1Src=RcvSvr1
Proc1Action1FrameType=FrameOnly

[AcceptEvent1]
LocalPortCount=1
LocalPort1=23720
PeerIPaddrCount=1
PeerIPaddr1=172.18.220.60
SessionGroup=SG_SVR1
SessionGroupDefine=PIPPLP
# 서버 세션 수 제한기능 - 0:제한없음 1:제한(최종세션종료) 2:제한(최초세션종료)
SessionLimit=0     # 제한 없음
ProcCount=0

