# ROME+ Application Make Property include
include $(ROME_HOME)/work/cruztp.mkconf
include $(CL_HOME)/work/cl.mkconf

# Module Name 
SRCS2	= test_iso.c iso_xml.c iso_utils.c 
DEST2	= test_iso

SRCS3	= validate_xml.c parson.c
DEST3	= validate_xml

SRCS4	= validate_xml_complex.c parson.c
DEST4	= validate_xml_complex

include $(ROME_HOME)/work/rome.mkrule

# Include Path
#INISAFENET_HOME=$(HOME)/INITEC/INISAFE_HP
INCS += -I$(CL_HOME)/inc
INCS += -I$(INISAFENET_HOME)/include 
INCS += -I.

PROC_INC += $(INCS:-I%=include=%)

# Library Link
#COMMON_LIB += -lrmpst -lrmvc -lrdf -lrsof
#COMMON_LIB += -ltgl_s_nh -lsmt
COMMON_LIB = -lc -lpthread
COMMON_LIB += $(XMLLIB)


# Compile Option
#DEFINES	+= -D_DEBUG_
#	암복호화
DEFINES	+= -D_CRYPT_
DEFINES	+= -DISO_TEST
DEFINES	+= -D__USE_XML_PARSER__

install: all bininstall
clobber: clean binclobber
