######################################################################################
#
# Ver 1.0 (2014.02.17)
#
######################################################################################

######################################################################################
[COMMON]                # 공통 정보 필드
max_group_count=1       # 최대 GROUP 갯수 (default:1) GROUP당 채널
max_group_per_ch=64     # GROUP당 최대 수용 채널 갯수 (max & default:100)
max_chid_count=64       # CHID 갯수
sim_ip=11.1.2.81        # Simulator IP(default:127.0.0.1)
bind_ip=11.1.1.37       # Simulator 접속을 위한 BIND IP (default:127.0.0.1)
port=40200
listen=50066


[GROUP]                 # GROUP 정보 필드
group_main=TEST_SIMX    # MAIN GROUP 서비스 명 (FEP 엔진와 연계 및 group 분기 처리)
group_1=SIMADT2         # CHID GROUP 서비스 명

