##########################################################
# 한국은행 TCP/IP 일괄 File 송신을 위한  Action 정보 및
# 기본 정보 Configuration
[BOK1_S]
PeerIP=10.103.10.13			# BOK IP 주소 (S)
PeerPort=61329				# BOK Port 번호 (S)
MainTimer=30 # 기본 수신 Timer(sec) (SR)
ResendTimer=30 # 송신 실패 시 재송신 Timer(sec) (SR)
SendSleepTime=1000 # DATA 송신 시 Frame wait Time (msec) (S)
MaxDataByte=4096 # Data 송신 시 Frame 최대 size (SR)
AutoRecovery=no # 장애 복구 option(yes/no) (R)
ChanID=BOK1 # 채널ID
AdtSvc=BOK1 # Adaptor Svc Name (SR)
BankCode=032 # Bank code  (S/R)
UserID=BOK # UserID (R)
RztSvc=CFM_RZT_PRC # 결과처리서비스명 (S) 
IdleTimer=20 # Idle Timer의 Timeout Interval
ComCode=BOK # 참가기관 코드 (중앙회)
IDFilePath=/MCXNAS/BOK1/bok_idpw.ini # ID.PW
LogFile_Trace=1 # 로그를 남기기 위한 조건 ( 1:ON / 0:OFF )
Max_Logfile_Size=1024000 # Max_Logfile_Size=1024000  (로그파일최대크기)


[BOK1_R]
PeerIP=10.103.10.13 # BOK IP 주소 (S)
PeerPort=61329 # BOK Port 번호 (S)
MainTimer=20 # 기본 수신 Timer(sec) (SR)
ResendTimer=10 # 송신 실패 시 재송신 Timer(sec) (SR)
SendSleepTime=10 # DATA 송신 시 Frame wait Time (msec) (S)
MaxDataByte=1024 # Data 송신 시 Frame 최대 size (SR)
AutoRecovery=no # 장애 복구 option(yes/no) (R)
BankCode=032 # Bank code  (S/R)
ComCode=BOK # 업무구분코드
UserID=BOK # UserID (R)
ChanID=BOK1 # 채널ID
EgnSvc=CFM_E2B_MST # Engine Svc Name (R)
AdtSvc=BOK1 # Driver Svc Name (SR)
RDirBase=/log/mcx/file/BOK1/rcv/work # 수신 Dir (R)
IdleTimer=100 # Idle Timer의 Timeout Interval
IDFilePath=/MCXNAS/BOK1/bok_idpw.ini # ID.PW
LogFile_Trace=1 # 로그를 남기기 위한 조건 ( 1:ON / 0:OFF )
Max_Logfile_Size=1024000  # (로그파일최대크기) 로그파일최대크기


##########################################################
# 신한국은행 TCP/IP 일괄 File 송신을 위한  Action 정보 및
# 기본 정보 Configuration
[BOK4_S]
PeerIP=10.3.1.7			# BOK IP 주소 (S)
PeerPort=23221			# BOK Port 번호 (S)
MainTimer=30			# 기본 수신 Timer(sec) (SR)
ResendTimer=10			# 송신 실패 시 재송신 Timer(sec) (SR)
SendSleepTime=100		# DATA 송신 시 Frame wait Time (msec) (S)
MaxDataByte=4096		# Data 송신 시 Frame 최대 size (SR)
AutoRecovery=no			# 장애 복구 option(yes/no) (R)
ChanID=BOK4				# 채널ID
AdtSvc=BOK4				# Adaptor Svc Name (SR)
BankCode=1328 			# Bank code  (S/R)
UserID=BOK 				# UserID (R)
RztSvc=CFM_RZT_PRC		# 결과처리서비스명 (S) 
IdleTimer=20			# Idle Timer의 Timeout Interval
ComCode=FTP				# 업무코드
LogFile_Trace=1			# 로그를 남기기 위한 조건 ( 1:ON / 0:OFF )
Max_Logfile_Size=1024000	# Max_Logfile_Size=1024000  (로그파일최대크기)


[BOK4_R]
PeerIP=10.3.1.7			# BOK IP 주소 (S)
PeerPort=23221			# BOK Port 번호 (S)
MainTimer=60			# 기본 수신 Timer(sec) (SR)
ResendTimer=10			# 송신 실패 시 재송신 Timer(sec) (SR)
SendSleepTime=100		# DATA 송신 시 Frame wait Time (msec) (S)
MaxDataByte=1024		# Data 송신 시 Frame 최대 size (SR)
AutoRecovery=no			# 장애 복구 option(yes/no) (R)
BankCode=1328			# Bank code  (S/R)
ComCode=FTP				# 업무구분코드
UserID=BOK				# UserID (R)
ChanID=BOK4				# 채널ID
EgnSvc=CFM_E2B_MST		# Engine Svc Name (R)
AdtSvc=BOK4				# Driver Svc Name (SR)
RDirBase=/log/mcx/file/BOK4/rcv/work	# 수신 Dir (R)
IdleTimer=100 			# Idle Timer의 Timeout Interval
LogFile_Trace=0			# 로그를 남기기 위한 조건 ( 1:ON / 0:OFF )
Max_Logfile_Size=1024000  # (로그파일최대크기)# 로그파일최대크기

################################################################
# 0312
# 신한국은행 TCP/IP 일괄 File 송신을 위한  Action 정보 및
[BOKB_S]
MainTimer=60			# 기본 수신 Timer(sec) (SR)
ResendTimer=10			# 송신 실패 시 재송신 Timer(sec) (SR)
SendSleepTime=100		# DATA 송신 시 Frame wait Time (msec) (S)
MaxDataByte=4096		# Data 송신 시 Frame 최대 size (SR)
RztSvc=CFM_RZT_PRC		# 결과처리서비스명 (S) 
OrgCode=1328 			# Bank code  (S/R)
BizCode=FTP				# 업무코드
LogFile_Trace=1			# 로그를 남기기 위한 조건 ( 1:ON / 0:OFF )
Max_Logfile_Size=1024000	# Max_Logfile_Size=1024000  (로그파일최대크기)
ChanID=BOKB # 채널ID


[BOKB_R]
MainTimer=60			# 기본 수신 Timer(sec) (SR)
ResendTimer=10			# 송신 실패 시 재송신 Timer(sec) (SR)
SendSleepTime=100		# DATA 송신 시 Frame wait Time (msec) (S)
MaxDataByte=1024		# Data 송신 시 Frame 최대 size (SR)
AutoRecovery=no			# 장애 복구 option(yes/no) (R)
OrgCode=1328			# Bank code  (S/R)
BizCode=FTP				# 업무구분코드
EgnSvc=CFM_E2B_MST		# Engine Svc Name (R)
RDirBase=/log/mcx/file/BOKB/rcv/work	# 수신 Dir (R)
#IdleTimer=100 			# Idle Timer의 Timeout Interval
LogFile_Trace=0			# 로그를 남기기 위한 조건 ( 1:ON / 0:OFF )
Max_Logfile_Size=1024000  # (로그파일최대크기)# 로그파일최대크기
ChanID=BOKB # 채널ID



################################################################
# 0312
# 국고
[BOKD_S]
MainTimer=60			# 기본 수신 Timer(sec) (SR)
ResendTimer=10			# 송신 실패 시 재송신 Timer(sec) (SR)
SendSleepTime=100		# DATA 송신 시 Frame wait Time (msec) (S)
MaxDataByte=4096		# Data 송신 시 Frame 최대 size (SR)
RztSvc=CFM_RZT_PRC		# 결과처리서비스명 (S) 
OrgCode="032 "			# Bank code  (S/R)
BizCode=BOK				# 업무코드
LogFile_Trace=1			# 로그를 남기기 위한 조건 ( 1:ON / 0:OFF )
Max_Logfile_Size=1024000	# Max_Logfile_Size=1024000  (로그파일최대크기)
ChanID=BOKD # 채널ID


[BOKD_R]
MainTimer=60			# 기본 수신 Timer(sec) (SR)
ResendTimer=10			# 송신 실패 시 재송신 Timer(sec) (SR)
SendSleepTime=100		# DATA 송신 시 Frame wait Time (msec) (S)
MaxDataByte=1024		# Data 송신 시 Frame 최대 size (SR)
AutoRecovery=no			# 장애 복구 option(yes/no) (R)
OrgCode="032 "			# Bank code  (S/R)
BizCode=BOK				# 업무구분코드
EgnSvc=CFM_E2B_MST		# Engine Svc Name (R)
RDirBase=/log/mcx/file/BOKD/rcv/work	# 수신 Dir (R)
#IdleTimer=100 			# Idle Timer의 Timeout Interval
LogFile_Trace=0			# 로그를 남기기 위한 조건 ( 1:ON / 0:OFF )
Max_Logfile_Size=1024000  # (로그파일최대크기)# 로그파일최대크기
ChanID=BOKD # 채널ID


