[Local]
SMTInfoFile=/ksfcsw/direa_dev/CruzLink/cfr_home/adaptor/smt_OAL2.xml
RMPRuleFile=/ksfcsw/direa_dev/CruzLink/cfr_home/adaptor/rmp_OAL2.ini
TGLRuleFile=/ksfcsw/direa_dev/CruzLink/cfr_home/adaptor/tgl_OAL2.ini
SvcName=OAL2

#File Trace Flag [ 0:미사용, 1:사용 default:미사용 ]
FileTrace=0
#File Trace Size [ defalut=512 MAX=1024 ]
FileTraceSize=103
#File Trace Log File Size [ default=5242880 ]
#TraceLogFileSize=10240
#File Trace Log File Count [ default=5 ]
TraceFileMaxNo=3


[RDFsetup]
MaxFrameSize=60000
UseTimer=yes
CutOffTime=1000


[inisafe]
#conf=/home/knbfep/INITEC/initec/INISAFE_Net/conf/INISAFENet_BOK.cnf
conf=/ksfcsw/direa_dev/initech/inisafenet/conf/INISAFENet_n.cnf



[SessionInfo]
# 연결된 세션이 0개이하면 끊어진 상태
DownSessCnt=0
# 연결된 세션이 1개이상이면 연결 상태
UpSessCnt=1
# 자동 세션 Close 사용여부 [0:미사용, 1:사용]
AutoDisCnt=0
# 자동 세션 Close 주기 (단위:sec, default : 60)
DisCntInterval=300

# 세션관리 여부 [0:미사용, 1:사용] (default : 1)
SessMoniter=0
# 세션관리서비스명
SessMgrSvc=rpsmgr
# 대외기관 채널코드
VanCode=OAL2


[PollInfo]
# Poll 사용여부 [0:미사용, 1:사용] (default : 0)
UsePoll=0
# Poll 주기 (단위:sec, default:60)
PollInterval=60
PollTimeOut=30


[BOK_CONFIG]
ENC_YN=Y
PW_PATH=/ksfcsw/direa_dev/CruzLink/cl_home/cfg/bok

#SEQ_PATH=$ROME_HOME/log
SEQ_PATH=/ksfcdat/direa_dev/cfg

BizCode=FTP
OrgCode=8070
BokCode=1016

[Monitoring]
SmtFlag=1       # 세션 모니터링 툴 사용 여부 (1:사용, 0:미사용:default)
CellCount=10    # 최대 세션 수

[Transform]
AgentIP=127.0.0.1
AgentPortXml=58110
AgentPortFix=58111
RequestTimeout=15
