#      Tcp/IP  NAT : 172.20.1.204
[Local]
SMTInfoFile=/app/mcx/pgm/cruzlink/adt/batch/12.BankOfKorea/smt_BOKB_S.xml
RMPRuleFile=/app/mcx/pgm/cruzlink/adt/batch/12.BankOfKorea/rmp_BOKB_S.ini
TGLRuleFile=/app/mcx/pgm/cruzlink/adt/batch/12.BankOfKorea/tgl_BOKB_S.ini
SvcName=BOKB_S
BizCode=FTP # NEW한은망

[inisafe]
conf=/app/mcx/initech/INISAFE_Net_for_C/conf/INISAFENet_PSB.cnf

[BOK_CONFIG]
ENC_YN=YES      # NO means no Encryption.(default : YES)

#File Trace Flag [ 0:미사용, 1:사용 default:미사용 ]
FileTrace=1
#File Trace Size [ defalut=512 MAX=1024 ]
FileTraceSize=1024
#File Trace Log File Size [ default=5242880 ]
#TraceLogFileSize=1300
#File Trace Log File Count [ default=5 ]
TraceFileMaxNo=3

[RSWQsetup]
ShmKey=0xd0080021
WQmaxSize=420000        # MaxDataByte * 101(1024 * 101) + ActionTable Area(524~600)

[RDFsetup]
MaxFrameSize=4000
UseTimer=yes
CutOffTime=1000

[SessionInfo]
# 연결된 세션이 0개이하면 끊어진 상태
DownSessCnt=0
# 연결된 세션이 1개이상이면 연결 상태
UpSessCnt=1
# 자동 세션 Close 사용여부 [0:미사용, 1:사용]
AutoDisCnt=0
# 자동 세션 Close 주기 (단위:sec, default : 60)
DisCntInterval=300

# 세션관리 여부 [0:미사용, 1:사용] (default : 1)
SessMoniter=0
# 세션관리서비스명
SessMgrSvc=CFM_SES_CORE
# 대외기관 채널코드
VanCode=BOKB_S
