[Local]
SMTInfoFile=/app/mcx/pgm/cruzlink/adt/online/ExtEnd/38.BankOfKorea/smt_BOKC.xml
RMPRuleFile=/app/mcx/pgm/cruzlink/adt/online/ExtEnd/38.BankOfKorea/rmp_BOKC.ini
TGLRuleFile=/app/mcx/pgm/cruzlink/adt/online/ExtEnd/38.BankOfKorea/tgl_BOKC.ini
SvcName=BOKC
BizCode=BOK # 국고

# 국고 
OrgCode=1328 # 참가기관코드(BANK)
BokCode=1016 # BOK기관코드(BOK)

[PollInfo]
UsePoll=0           # 0 : Not to use Poll in FEP (default : 0 )
PollInterval=1800   # 30 minutes : 30 * 60 seconds (default : 600 seconds)
PollTimeOut=180     #  3 minutes :  3 * 60 seconds (default :  60 seconds)

[inisafe]
conf=/app/mcx/initech/INISAFE_Net_for_C/conf/INISAFENet_PSB.cnf

[BOK_CONFIG]
ENC_YN=YES      # NO means no Encryption.(default : YES)

#File Trace Flag [ 0:미사용, 1:사용 default:미사용 ]
FileTrace=1
#File Trace Size [ defalut=512 MAX=1024 ]
FileTraceSize=1024
#File Trace Log File Size [ default=5242880 ]
#TraceLogFileSize=1300
#File Trace Log File Count [ default=5 ]
TraceFileMaxNo=3

[RDFsetup]
MaxFrameSize=4000
UseTimer=yes
CutOffTime=1000

[SessionInfo]
# 연결된 세션이 0개이하면 끊어진 상태
DownSessCnt=0
# 연결된 세션이 1개이상이면 연결 상태
UpSessCnt=1
# 자동 세션 Close 사용여부 [0:미사용, 1:사용]
AutoDisCnt=0
# 자동 세션 Close 주기 (단위:sec, default : 60)
DisCntInterval=300

# 세션관리 여부 [0:미사용, 1:사용] (default : 1)
SessMoniter=0
# 세션관리서비스명
SessMgrSvc=CFR_SES_CORE
# 대외기관 채널코드
VanCode=BOKC
