[Local]
#SMTInfoFile=/home/knbfep/pgm/cl_home/adt/BOK/smt_ISO.xml
RMPRuleFile=/home/knbfep/pgm/cl_home/adt/BOK/rmp_ISO.xml
TGLRuleFile=/home/knbfep/pgm/cl_home/adt/BOK/tgl_ISO.xml
SvcName=ISO

#File Trace Flag [ 0:미사용, 1:사용 default:미사용 ]
FileTrace=1
#File Trace Size [ defalut=512 MAX=1024 ]
FileTraceSize=1024
#File Trace Log File Size [ default=5242880 ]
#TraceLogFileSize=1300
#File Trace Log File Count [ default=5 ]
TraceFileMaxNo=3


[RDFsetup]
MaxFrameSize=4000
UseTimer=yes
CutOffTime=1000


[BOK_CONFIG]
# YES or NO (default : YES)
ENC_YN=YES                                      
# (SHB ONLY) BOK LOGIN INF ini filename
LOGIN_INF_FILE=/xnsftp/common_ini/new_bok_idpw2.ini      
# Default : FTP
BizCode=FTP
# BOK Code
BokCode=1016
# (KSFC) 증권금융
OrgCode=8070
# (KSFC ONLY) Sequence File Path
SEQ_PATH=$ROME_HOME/log

[inisafe]
#conf=/app/mcx/initech/INISAFE_Net_for_C/conf/INISAFENet_PSB.cnf
conf=/home/knbfep/INITEC/initec/INISAFE_Net/conf/INISAFENet_BOK.cnf

[SessionInfo]
# 연결된 세션이 0개이하면 끊어진 상태
DownSessCnt=0
# 연결된 세션이 1개이상이면 연결 상태
UpSessCnt=1
# 자동 세션 Close 사용여부 [0:미사용, 1:사용]
AutoDisCnt=0
# 자동 세션 Close 주기 (단위:sec, default : 60)
DisCntInterval=300

# 세션관리 여부 [0:미사용, 1:사용] (default : 1)
SessMoniter=0
# 세션관리서비스명
SessMgrSvc=rpsmgr
# 대외기관 채널코드
VanCode=ISO

[PollInfo]
UsePoll=0			# 0 : Not to use Poll in FEP (default : 0 )
PollInterval=600    # 10 minutes : 10 * 60 seconds (default : 600 seconds)
PollTimeOut=60      #  1 minutes :  (default :  60 seconds)

[Monitoring]
SmtFlag=1
CellCount=10
