[Local]
#SMTInfoFile=/home/knbfep/pgm/cl_home/adt/BOK/smt_ISO.xml
RMPRuleFile=/home/knbfep/pgm/cl_home/adt/BOK/rmp_ISO.xml
TGLRuleFile=/home/knbfep/pgm/cl_home/adt/BOK/tgl_ISO.xml
SvcName=ISO

BizCode=FTP
OrgCode=KNB
BokCode=1016

SEQ_PATH=$ROME_HOME/log


[BOK_CONFIG]
ENC_YN=YES                                      # YES or NO (default : YES)

        
        
[inisafe]
#conf=/app/mcx/initech/INISAFE_Net_for_C/conf/INISAFENet_PSB.cnf
conf=/home/knbfep/INITEC/initec/INISAFE_Net/conf/INISAFENet_BOK.cnf
